### ISSUE TITLE
/lunch duplicates davenport results

### ISSUE THREAD

**Issue by Benuuu** [IntrepidPursuits/KevinBot#9]

**Comment by lizvdk** [comment]
I will look into it on Friday.

**Comment by lizvdk** [comment]
@Benuuu 
I took a quick look into this issue. The vendors are duplicated on the fooda website. 😱  
![davenport-dupe](https://cloud.githubusercontent.com/assets/7101137/18677727/cd13708e-7f27-11e6-8655-2fa019d30f90.png)

I will add some logic that will weed out duplicates.

**Comment by Benuuu** [comment]
@lizvdk, it's probably not worth the effort.  I'm just going to close this instead.
